### ISSUE TITLE
Fracture prefix and suffix are mixed up in the script

### ISSUE THREAD

**Issue by archevil** [SteffenBlake/FarmersMarket#17]
Title, should be an easy fix. Thank you for the tool :)

**Comment by anthcho** [comment]
And missing "at" with suffix code

RAW_Fracture_3Suffix := "Fracture a random Suffix on an item with at least 3 Suffixes"
RAW_Fracture_3Prefix := "Fracture a random Prefix on an item with at least 3 Prefixes"

**Comment by Helban** [comment]
fixed, thanks
