### ISSUE TITLE
Script stops working some times

### ISSUE THREAD

**Issue by ikelso** [SteffenBlake/FarmersMarket#2]
after pricing a random number of items, the keybind stops functioning.  I'll use the keybind and it will successfully price a station, but then it will not recognize the keybind has been pressed or start a new pricing loop.  A Reload of the script gets it working again such as 

`^!r::Reload`

**Comment by SteffenBlake** [comment]
Looks like its related to the lack of a timeout on the `ClipWait` portion, when you press the hotkey while not hovering over an item.

- [ ] We need to add a timeout to the `ClipWait`
