### ISSUE TITLE
Pricing is sometimes incorrect

### ISSUE THREAD

**Issue by ikelso** [SteffenBlake/FarmersMarket#3]
I'm not sure what the root cause is of this, but pricing items seems to be incorrect in multiple cases. 

My config value for remove/add caster is `RmvAdd_Caster:= "30c"`

In game, the ahk script prices the station with `#15c`

In another instance, I have aug chaos lucky set with `AugmentLucky_Chaos:= "60c"`
In game the tool prices it as 30c though.

**Comment by SteffenBlake** [comment]
This will be a Sub-Issue of #12
