### ISSUE TITLE
Mispriced Removed+Add Critical Modifier

### ISSUE THREAD

**Issue by brakthir** [SteffenBlake/FarmersMarket#8]
Rarity: Currency
Horticrafting Station
--------
Stack Size: 1/5,000
Crafts: 3/3
--------
Stores a limited number of Harvest crafting options for later use
Remove a random Critical modifier from an item and add a new Critical modifier (82) (crafted)
Reroll the values of Prefix, Suffix and Implicit modifiers on a Rare item, with Lucky modifier values (83) (crafted)
Reroll the values of Prefix, Suffix and Implicit modifiers on a Rare item, with Lucky modifier values (83) (crafted)
--------
Right-click this item then left-click a location within the Sacred Grove to place it.
--------
Note: #/90c/20c/20c

I manually readjusted it back to 90c, it keeps pasting it as 30c.

**Comment by SteffenBlake** [comment]
This will be a Sub-Issue of #12
